jobs:
  include:
  - stage: deploy
    language: node_js
    node_js:
    - 10
    cache:
      directories:
      - "./node_modules"
    script:
    - cd frontend
    - npm install
    - ng build --prod --aot
    before_deploy:
    - cd dist/frontend
deploy:
  provider: s3
  access_key_id: AKIA6QW6FCJ65WNUMV2A
  secret_access_key:
    secure: i7GWoIrjpqBy4PKGiciqZXoMfpcUY4FLnIvtF66sZHS5WdfI9NRxMqVF9UjE2qfXaJDGrmunwTTiajxxS3nMrrCJHF1N4lnCRLykmQNLP5cYgHPqIhgNnQ/52nBwuZM7nJQD3S1LGtBuKM8eIqh31gcGKdbML7VoLbp7MXoOdWtNv7PnqGcI/oCjGMBwcRHaIvyru+fiwLWkDeCKXLNc1Yu+4MvvSSs+fNZtMqm8H4BvA8XENUaNozr6UI2oAASYFsZjmKzJr1Gu/gZIr5pUa5f371Qb718hbNBJwcYztj1obwgIG09OyROz51f+Fe3P/NtldJRLjm6d4G6qu4m6MIXp8iXh61Pssh3gCk0SJcNuDAnZsWEt2R+pojORvpSHIYIqkFKIOnXYJsWv8eu4x7QaVXZxQb0jPr8jlHXszjf+nhVe01XNJ/QQxqSyM96vm84bKv9bqzhGqlOzyEKJiKw6eaj1Q5HAs7GvLxgUkq/q2neYuPUewLpmRW8EAVrSP/fMvXlwuD9OBy6rDw6xQc8v/dB54PDe9A7pJ2MKv59IErl8ddXaatiysplmFf5vZF762F1lMS7KFgkrjvdMawTtc+NsektrxtokkuMgak+lKDFwWwWmvkyPQJZF+yoJ+hnhX23da+QpHLwyxOvqeW8d6cpf8Vdl54TjibKVrME=
  bucket: sailor-hathaway-budget-frontend
  acl: public_read
  skip_cleanup: true
  on:
    repo: johnchase/budget-app
