jobs:
  include:
  - stage: deploy
    language: node_js
    node_js:
    - 10
    cache:
      directories:
      - "./node_modules"
    script:
    - cd frontend
    - npm install
    - ng build --prod --aot
    before_deploy:
    - cd dist/frontend
deploy:
  provider: s3
  access_key_id: AKIA6QW6FCJ6ZUF2XSFJ
  secret_access_key:
    secure: TcFA55SvgkygqjkSr2JAZ6zlSRDwYyYMIaH6WE75REYvogX5kEg8j2NnijDyORY8vgStoiGARd5SGlOobOI5Gwd+NZ447c/rrggKiCiD2okTs0V4qHCx8VlzBTIuHafk7lfZYvBQCZzZLfsh6TAiSfGsjhz2i1zTRKRkt6uSHjxDWBmESEimJCfMc2mlCPubLGqWams/DIkRJaznihyJvyjpQqiIUMl2ftDI0/vwJovooTZr6nW4Eg01rqaUr5EfrtOzVZ/D91kz3kgdXC9oiupfj/06rInclQeZhAf7avwhg48LAJwJq8pIfpC2bj9czlIdMrQDyzaye0ocjnYjxV2KPHQOjaX9wJ6gZdrdSEEYyqEg1otesnuY4VNqk9dGCUpvScRrfjNABsa1svINas8yKJbXfb19Lknh9OjTxY2AGY5BwbScnHNblSeE28cfq4R7sFi4JsUj+2TI2E5NEjC3KHwzOyEAi5qxARS+7g2JB1P801ztkEdLUkccd1Sldk4QXWOOc301l8RMrp+z4oTf/M7ziI6NrWYbkPgNr9V3rw5K4MAY1xPpOt79gf88s4x7HlIOCRzSNoldL4IggZQ/KC/Rbmjr/0ZciBUySGfMivUMjuD7WFYbxroyxepbJddgzvzTSkcpTATSMSUu+nGLY7thadyjmdCGMjfJGsA=
  bucket: sailor-hathaway-budget-frontend
  acl: public_read
  skip_cleanup: true
  on:
    repo: johnchase/budget-app
