jobs:
  include:
  - stage: deploy
    language: node_js
    node_js:
    - 10
    cache:
      directories:
      - "./node_modules"
    script:
    - cd frontend
    - npm install
    - ng build --prod --aot
    before_deploy:
    - cd dist/frontend
deploy:
  provider: s3
  access_key_id: AKIA6QW6FCJ6ZUF2XSFJ
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: sailor-hathaway-budget-frontend
  acl: public_read
  on:
    repo: johnchase/budget-app
