jobs:
  include:
  - stage: deploy
    language: node_js
    node_js:
    - 10
    cache:
      directories:
      - "./node_modules"
    script:
    - cd frontend
    - npm install
    - ng build --prod --aot
    before_deploy:
    - cd dist/frontend
deploy:
  provider: s3
  access_key_id: AKIA6QW6FCJ6ZUF2XSFJ
  secret_access_key:
    secure: oO0ovrZ42Rwdg8NUVa+H37EtjglLrZrscTFRtuYCRr4guxbCtmjZxjbDPWCXZk01Ras7eurireE/eDhSJHcVoIxaSbbaBRQEtO1CkVAaDqaBKyzgxrj6Bf8DxEjZ26Zd3hg84MKbCaMSK2wkYqV/kHWrSuHoPpDlmq2oqWXo3nXqAUOC92Bi5CgwvC+DXZLzLHGMxVhVie5spAWiu6nLJpAc/LgTsHzDVtjSIBWAgoEqgpF3oqOVP93ema9flMZ1iewjlXnM/eODsh7NSPVdI5phZo5/6KWY+CXpZGoO3Nw1EKvv/cAAbl6uRE3nVXXhJjYuXUdZTRpvGKei4vIyjxUzIoie40iQbUHskLeaiz7D9QbBKQE9kYBOsmlwFX5EToEw74z7wu9b3sH54cbdUyOVhrAods/8qeyrfwLVkdzMPN8LPfN7ShjVjuV9OBzb3parBYCrEg5VV8wTS6ipr2mKVtrWVJbEMkh13g5cuT1CvqsSEw98QqUudBIGjqB/Kk50d9pi7ISNMsz0YYtXQ/CICe91Sa7UsL07P1prpgkBuTOhaKUxe6iLvTNXny/Kn/BbveSItQ1d8OC2rME11rbfKz442m7O+qNN+UbM6TJouVT1k2LiBlBI7O4WnVHbInBU7czk5oEMQPmGM61Jy7+m9gMQVMCN9XRiKI7mqco=
  bucket: sailor-hathaway-budget-frontend
  acl: public_read
  on:
    repo: johnchase/budget-app
